Failuse case for 4_data_augment.py